name: Build Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ocpp-jars
        path: "**/build/libs/*.jar"