name: Build Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Execute Gradle build
      run: ./gradlew build
      
    - name: List build artifacts
      run: ls -R ocpp-v1_6/build/libs ocpp-v2_0/build/libs || echo "Artifacts not found"
      
    - name: Upload JAR artifacts
      if: success()
      uses: actions/upload-artifact@v3.1.3
      with:
        name: ocpp-jars
        path: |
          **/build/libs/*.jar
        retention-days: 90
        if-no-files-found: error